In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

ModuleNotFoundError: No module named 'tensorflow.python'

In [ ]:
df=pd.read_csv('historical_emissions.csv')
df

Country Data source                Sector  Gas    Unit  \
0                  World        CAIT  Total including LUCF  CO2  MtCO₂e   
1                  China        CAIT  Total including LUCF  CO2  MtCO₂e   
2          United States        CAIT  Total including LUCF  CO2  MtCO₂e   
3    European Union (27)        CAIT  Total including LUCF  CO2  MtCO₂e   
4                  India        CAIT  Total including LUCF  CO2  MtCO₂e   
..                   ...         ...                   ...  ...     ...   
190                Nauru        CAIT  Total including LUCF  CO2  MtCO₂e   
191               Tuvalu        CAIT  Total including LUCF  CO2  MtCO₂e   
192                 Niue        CAIT  Total including LUCF  CO2  MtCO₂e   
193                 Fiji        CAIT  Total including LUCF  CO2  MtCO₂e   
194                Ghana        CAIT  Total including LUCF  CO2  MtCO₂e   

         2018      2017      2016      2015      2014  ...      1999  \
0    36441.55  35588.70  35160.60  34521.91  34558.59  ...  24957.30   
1     9663.36   9367.67   9164.21   9120.27   9184.77  ...   2799.84   
2     4749.57   4581.90   4656.84   4563.52   4683.35  ...   5191.66   
3     2636.99   2692.12   2669.54   2321.61   2263.78  ...   3079.46   
4     2400.25   2267.16   2149.01   2085.38   2072.03  ...    683.00   
..        ...       ...       ...       ...       ...  ...       ...   
190      0.07      0.07      0.06      0.05      0.05  ...      0.09   
191      0.01      0.01      0.01      0.01      0.01  ...      0.01   
192      0.00      0.00      0.00      0.00      0.00  ...      0.01   
193     -0.65     -0.73     -0.81     -1.03     -1.24  ...     -1.74   
194     -8.82    -10.15    -10.82     44.53     43.77  ...     16.46   

         1998      1997      1996      1995      1994      1993      1992  \
0    24895.32  25292.92  24214.92  23890.22  23260.29  23124.00  22988.29   
1     2882.75   2779.27   2715.50   2735.48   2414.50   2294.12   2068.77   
2     5172.06   5129.29   4864.46   4708.31   4654.52   4581.76   4461.62   
3     3134.03   3142.23   3210.93   3113.68   3060.09   3072.40   3133.06   
4      618.73    600.38    555.60    519.98    466.79    431.31    409.09   
..        ...       ...       ...       ...       ...       ...       ...   
190      0.10      0.10      0.10      0.11      0.11      0.11      0.12   
191      0.01      0.01      0.01      0.01      0.01      0.01      0.01   
192      0.01      0.01      0.01      0.01      0.01      0.01      0.01   
193     -1.76     -1.74     -1.72     -1.78     -1.79     -1.79     -1.78   
194     15.98     14.18     13.98     13.60     13.34     13.07     12.96   

         1991      1990  
0    23056.40  22849.92  
1     1952.78   1823.96  
2     4389.50   4426.40  
3     3247.48   3286.44  
4      386.17    341.32  
..        ...       ...  
190      0.13      0.13  
191      0.00      0.00  
192      0.01      0.01  
193     -1.81     -1.81  
194     12.44     12.67  

[195 rows x 34 columns]

In [ ]:
df=df.drop(columns=['Data source','Sector','Gas','Unit'])

In [ ]:
negaraASEAN=['Indonesia', 'Thailand', 'Cambodia', 'Myanmar', 'Malaysia','Singapore','Philippines','Vietnam','Laos','Brunei']

In [ ]:
def praprocessing(dataframe):
    df_new=df.drop(labels=range(0,195),axis=0)
    
    for negara in negaraASEAN:
        arr=[]
        arr.append(dataframe.loc[dataframe['Country']==negara])
        df_new=df_new.append(arr,ignore_index=True)
    return df_new

In [ ]:
df_clean=praprocessing(df)

C:\Users\ihzaf\AppData\Local\Temp\ipykernel_9688\761560554.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new=df_new.append(arr,ignore_index=True)


In [ ]:
# df_clean.mul(100)
df_clean.iloc[:,1:] = df_clean.iloc[:,1:] * 100

In [ ]:
df_clean

Country      2018      2017      2016      2015      2014      2013  \
0    Indonesia  126955.0  108111.0  106810.0  157476.0  153923.0  125027.0   
1     Thailand   27090.0   27370.0   27379.0   26334.0   25938.0   26272.0   
2     Cambodia    4016.0    4038.0    3890.0    7351.0    7155.0    7050.0   
3      Myanmar   13692.0   13348.0   12578.0   12825.0   12463.0   12156.0   
4     Malaysia   31959.0   29810.0   31017.0   12454.0   13537.0   10959.0   
5    Singapore    4739.0    4746.0    4619.0    4545.0    4441.0    4387.0   
6  Philippines   14470.0   13905.0   12738.0   11610.0   10684.0   10023.0   
7      Vietnam   24536.0   20966.0   21170.0   18654.0   14644.0   13272.0   
8         Laos    2746.0    2718.0    2403.0    1732.0    1309.0    1258.0   
9       Brunei     747.0     703.0     679.0     635.0     737.0     736.0   

       2012      2011     2010  ...     1999     1998      1997     1996  \
0  130387.0  128569.0  77392.0  ...  84942.0  90796.0  148456.0  77238.0   
1   25233.0   23488.0  20237.0  ...  17418.0  16752.0   18850.0  18534.0   
2    7035.0    7011.0    850.0  ...    608.0    611.0     587.0    578.0   
3   11838.0   11479.0  13415.0  ...  15015.0  14901.0   14766.0  14808.0   
4    9192.0    9213.0  31620.0  ...  22259.0  23395.0   21434.0  20621.0   
5    4364.0    4472.0   4236.0  ...   3842.0   3794.0    3945.0   3981.0   
6    9049.0    8690.0   8595.0  ...   7484.0   7733.0    7773.0   6990.0   
7   12461.0   12639.0  16768.0  ...  -2725.0  -2751.0   -3240.0  -3830.0   
8    1194.0    1171.0   1505.0  ...   1135.0   1132.0    1129.0   1125.0   
9     748.0     736.0    811.0  ...    550.0    874.0     658.0    607.0   

      1995     1994     1993     1992     1991     1990  
0  90921.0  88131.0  86988.0  85530.0  84623.0  83239.0  
1  16683.0  14839.0  13423.0  11961.0  10985.0  10074.0  
2    568.0    564.0    555.0    552.0    547.0    543.0  
3  14894.0  14762.0  14679.0  14626.0  14610.0  14617.0  
4  19788.0  19120.0  18540.0  18309.0  17754.0  17040.0  
5   3883.0   3919.0   3732.0   3213.0   3124.0   2967.0  
6   6421.0   5390.0   4987.0   4614.0   4277.0   4325.0  
7  -4195.0  -4554.0  -4804.0  -5298.0  -5398.0  -5388.0  
8   1117.0   1114.0   1111.0   1110.0   1105.0   1102.0  
9    603.0    566.0    538.0    510.0    490.0    543.0  

[10 rows x 30 columns]

In [ ]:
# for i in range(len(df_clean)):
row=df_clean.columns.values.tolist()
row.pop(0)
# print(row)
country=df_clean.iloc[:,0].values.tolist()
# country

In [ ]:
df_trans=df_clean.T

In [ ]:
new_header = df_trans.iloc[0] #grab the first row for the header
df_trans = df_trans[1:] #take the data less the header row
df_trans.columns = new_header #set the header row as the df header

In [ ]:
df_trans.head()

Country Indonesia Thailand Cambodia  Myanmar Malaysia Singapore Philippines  \
2018     126955.0  27090.0   4016.0  13692.0  31959.0    4739.0     14470.0   
2017     108111.0  27370.0   4038.0  13348.0  29810.0    4746.0     13905.0   
2016     106810.0  27379.0   3890.0  12578.0  31017.0    4619.0     12738.0   
2015     157476.0  26334.0   7351.0  12825.0  12454.0    4545.0     11610.0   
2014     153923.0  25938.0   7155.0  12463.0  13537.0    4441.0     10684.0   

Country  Vietnam    Laos Brunei  
2018     24536.0  2746.0  747.0  
2017     20966.0  2718.0  703.0  
2016     21170.0  2403.0  679.0  
2015     18654.0  1732.0  635.0  
2014     14644.0  1309.0  737.0

In [ ]:
Indonesia=df_trans.iloc[:,0].values.tolist()
Indonesia

[126955.0,
 108110.99999999999,
 106809.99999999999,
 157476.0,
 153923.0,
 125027.0,
 130386.99999999999,
 128569.0,
 77392.0,
 103671.0,
 73176.0,
 73857.0,
 115283.0,
 82993.0,
 103149.0,
 76193.0,
 100139.0,
 63116.0,
 79562.0,
 84942.0,
 90796.0,
 148456.0,
 77238.0,
 90921.0,
 88131.0,
 86988.0,
 85530.0,
 84623.0,
 83239.0]

In [ ]:
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [ ]:
n_steps = 5
X, y = splitSequence(Indonesia, n_steps = 5)

In [ ]:
print(X)

[[126955. 108111. 106810. 157476. 153923.]
 [108111. 106810. 157476. 153923. 125027.]
 [106810. 157476. 153923. 125027. 130387.]
 [157476. 153923. 125027. 130387. 128569.]
 [153923. 125027. 130387. 128569.  77392.]
 [125027. 130387. 128569.  77392. 103671.]
 [130387. 128569.  77392. 103671.  73176.]
 [128569.  77392. 103671.  73176.  73857.]
 [ 77392. 103671.  73176.  73857. 115283.]
 [103671.  73176.  73857. 115283.  82993.]
 [ 73176.  73857. 115283.  82993. 103149.]
 [ 73857. 115283.  82993. 103149.  76193.]
 [115283.  82993. 103149.  76193. 100139.]
 [ 82993. 103149.  76193. 100139.  63116.]
 [103149.  76193. 100139.  63116.  79562.]
 [ 76193. 100139.  63116.  79562.  84942.]
 [100139.  63116.  79562.  84942.  90796.]
 [ 63116.  79562.  84942.  90796. 148456.]
 [ 79562.  84942.  90796. 148456.  77238.]
 [ 84942.  90796. 148456.  77238.  90921.]
 [ 90796. 148456.  77238.  90921.  88131.]
 [148456.  77238.  90921.  88131.  86988.]
 [ 77238.  90921.  88131.  86988.  85530.]
 [ 90921.  

In [ ]:
for i in range(len(X)):
    print(X[i], y[i])

[126955. 108111. 106810. 157476. 153923.] 125027.0
[108111. 106810. 157476. 153923. 125027.] 130386.99999999999
[106810. 157476. 153923. 125027. 130387.] 128569.0
[157476. 153923. 125027. 130387. 128569.] 77392.0
[153923. 125027. 130387. 128569.  77392.] 103671.0
[125027. 130387. 128569.  77392. 103671.] 73176.0
[130387. 128569.  77392. 103671.  73176.] 73857.0
[128569.  77392. 103671.  73176.  73857.] 115283.0
[ 77392. 103671.  73176.  73857. 115283.] 82993.0
[103671.  73176.  73857. 115283.  82993.] 103149.0
[ 73176.  73857. 115283.  82993. 103149.] 76193.0
[ 73857. 115283.  82993. 103149.  76193.] 100139.0
[115283.  82993. 103149.  76193. 100139.] 63116.0
[ 82993. 103149.  76193. 100139.  63116.] 79562.0
[103149.  76193. 100139.  63116.  79562.] 84942.0
[ 76193. 100139.  63116.  79562.  84942.] 90796.0
[100139.  63116.  79562.  84942.  90796.] 148456.0
[ 63116.  79562.  84942.  90796. 148456.] 77238.0
[ 79562.  84942.  90796. 148456.  77238.] 90921.0
[ 84942.  90796. 148456.  77238.

In [ ]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[126955.]
  [108111.]
  [106810.]
  [157476.]
  [153923.]]

 [[108111.]
  [106810.]
  [157476.]
  [153923.]
  [125027.]]]
