In [144]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [145]:
df=pd.read_csv('historical_emissions.csv')
df

Country Data source                Sector  Gas    Unit  \
0                  World        CAIT  Total including LUCF  CO2  MtCO₂e   
1                  China        CAIT  Total including LUCF  CO2  MtCO₂e   
2          United States        CAIT  Total including LUCF  CO2  MtCO₂e   
3    European Union (27)        CAIT  Total including LUCF  CO2  MtCO₂e   
4                  India        CAIT  Total including LUCF  CO2  MtCO₂e   
..                   ...         ...                   ...  ...     ...   
190                Nauru        CAIT  Total including LUCF  CO2  MtCO₂e   
191               Tuvalu        CAIT  Total including LUCF  CO2  MtCO₂e   
192                 Niue        CAIT  Total including LUCF  CO2  MtCO₂e   
193                 Fiji        CAIT  Total including LUCF  CO2  MtCO₂e   
194                Ghana        CAIT  Total including LUCF  CO2  MtCO₂e   

         2018      2017      2016      2015      2014  ...      1999  \
0    36441.55  35588.70  35160.60  34521.91  34558.59  ...  24957.30   
1     9663.36   9367.67   9164.21   9120.27   9184.77  ...   2799.84   
2     4749.57   4581.90   4656.84   4563.52   4683.35  ...   5191.66   
3     2636.99   2692.12   2669.54   2321.61   2263.78  ...   3079.46   
4     2400.25   2267.16   2149.01   2085.38   2072.03  ...    683.00   
..        ...       ...       ...       ...       ...  ...       ...   
190      0.07      0.07      0.06      0.05      0.05  ...      0.09   
191      0.01      0.01      0.01      0.01      0.01  ...      0.01   
192      0.00      0.00      0.00      0.00      0.00  ...      0.01   
193     -0.65     -0.73     -0.81     -1.03     -1.24  ...     -1.74   
194     -8.82    -10.15    -10.82     44.53     43.77  ...     16.46   

         1998      1997      1996      1995      1994      1993      1992  \
0    24895.32  25292.92  24214.92  23890.22  23260.29  23124.00  22988.29   
1     2882.75   2779.27   2715.50   2735.48   2414.50   2294.12   2068.77   
2     5172.06   5129.29   4864.46   4708.31   4654.52   4581.76   4461.62   
3     3134.03   3142.23   3210.93   3113.68   3060.09   3072.40   3133.06   
4      618.73    600.38    555.60    519.98    466.79    431.31    409.09   
..        ...       ...       ...       ...       ...       ...       ...   
190      0.10      0.10      0.10      0.11      0.11      0.11      0.12   
191      0.01      0.01      0.01      0.01      0.01      0.01      0.01   
192      0.01      0.01      0.01      0.01      0.01      0.01      0.01   
193     -1.76     -1.74     -1.72     -1.78     -1.79     -1.79     -1.78   
194     15.98     14.18     13.98     13.60     13.34     13.07     12.96   

         1991      1990  
0    23056.40  22849.92  
1     1952.78   1823.96  
2     4389.50   4426.40  
3     3247.48   3286.44  
4      386.17    341.32  
..        ...       ...  
190      0.13      0.13  
191      0.00      0.00  
192      0.01      0.01  
193     -1.81     -1.81  
194     12.44     12.67  

[195 rows x 34 columns]

In [146]:
df=df.drop(columns=['Data source','Sector','Gas','Unit'])

In [147]:
negaraASEAN=['Indonesia', 'Thailand', 'Cambodia', 'Myanmar', 'Malaysia','Singapore','Philippines','Vietnam','Laos','Brunei']

In [148]:
def praprocessing(dataframe):
    df_new=df.drop(labels=range(0,195),axis=0)
    
    for negara in negaraASEAN:
        arr=[]
        arr.append(dataframe.loc[dataframe['Country']==negara])
        df_new=df_new.append(arr,ignore_index=True)
    return df_new

In [149]:
df_clean=praprocessing(df)

C:\Users\ihzaf\AppData\Local\Temp\ipykernel_8444\761560554.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new=df_new.append(arr,ignore_index=True)


In [150]:
# df_clean.mul(100)
# df_clean.iloc[:,1:] = df_clean.iloc[:,1:] * 100

In [151]:
df_clean

Country     2018     2017     2016     2015     2014     2013     2012  \
0    Indonesia  1269.55  1081.11  1068.10  1574.76  1539.23  1250.27  1303.87   
1     Thailand   270.90   273.70   273.79   263.34   259.38   262.72   252.33   
2     Cambodia    40.16    40.38    38.90    73.51    71.55    70.50    70.35   
3      Myanmar   136.92   133.48   125.78   128.25   124.63   121.56   118.38   
4     Malaysia   319.59   298.10   310.17   124.54   135.37   109.59    91.92   
5    Singapore    47.39    47.46    46.19    45.45    44.41    43.87    43.64   
6  Philippines   144.70   139.05   127.38   116.10   106.84   100.23    90.49   
7      Vietnam   245.36   209.66   211.70   186.54   146.44   132.72   124.61   
8         Laos    27.46    27.18    24.03    17.32    13.09    12.58    11.94   
9       Brunei     7.47     7.03     6.79     6.35     7.37     7.36     7.48   

      2011    2010  ...    1999    1998     1997    1996    1995    1994  \
0  1285.69  773.92  ...  849.42  907.96  1484.56  772.38  909.21  881.31   
1   234.88  202.37  ...  174.18  167.52   188.50  185.34  166.83  148.39   
2    70.11    8.50  ...    6.08    6.11     5.87    5.78    5.68    5.64   
3   114.79  134.15  ...  150.15  149.01   147.66  148.08  148.94  147.62   
4    92.13  316.20  ...  222.59  233.95   214.34  206.21  197.88  191.20   
5    44.72   42.36  ...   38.42   37.94    39.45   39.81   38.83   39.19   
6    86.90   85.95  ...   74.84   77.33    77.73   69.90   64.21   53.90   
7   126.39  167.68  ...  -27.25  -27.51   -32.40  -38.30  -41.95  -45.54   
8    11.71   15.05  ...   11.35   11.32    11.29   11.25   11.17   11.14   
9     7.36    8.11  ...    5.50    8.74     6.58    6.07    6.03    5.66   

     1993    1992    1991    1990  
0  869.88  855.30  846.23  832.39  
1  134.23  119.61  109.85  100.74  
2    5.55    5.52    5.47    5.43  
3  146.79  146.26  146.10  146.17  
4  185.40  183.09  177.54  170.40  
5   37.32   32.13   31.24   29.67  
6   49.87   46.14   42.77   43.25  
7  -48.04  -52.98  -53.98  -53.88  
8   11.11   11.10   11.05   11.02  
9    5.38    5.10    4.90    5.43  

[10 rows x 30 columns]

In [152]:
# for i in range(len(df_clean)):
row=df_clean.columns.values.tolist()
row.pop(0)
# print(row)
country=df_clean.iloc[:,0].values.tolist()
# country

In [153]:
df_trans=df_clean.T

In [154]:
new_header = df_trans.iloc[0] #grab the first row for the header
df_trans = df_trans[1:] #take the data less the header row
df_trans.columns = new_header #set the header row as the df header

In [155]:
df_trans.head()

Country Indonesia Thailand Cambodia Myanmar Malaysia Singapore Philippines  \
2018      1269.55    270.9    40.16  136.92   319.59     47.39       144.7   
2017      1081.11    273.7    40.38  133.48    298.1     47.46      139.05   
2016       1068.1   273.79     38.9  125.78   310.17     46.19      127.38   
2015      1574.76   263.34    73.51  128.25   124.54     45.45       116.1   
2014      1539.23   259.38    71.55  124.63   135.37     44.41      106.84   

Country Vietnam   Laos Brunei  
2018     245.36  27.46   7.47  
2017     209.66  27.18   7.03  
2016      211.7  24.03   6.79  
2015     186.54  17.32   6.35  
2014     146.44  13.09   7.37

In [156]:
Indonesia=df_trans.iloc[:,0].values.tolist()
Indonesia

[1269.55,
 1081.11,
 1068.1,
 1574.76,
 1539.23,
 1250.27,
 1303.87,
 1285.69,
 773.92,
 1036.71,
 731.76,
 738.57,
 1152.83,
 829.93,
 1031.49,
 761.93,
 1001.39,
 631.16,
 795.62,
 849.42,
 907.96,
 1484.56,
 772.38,
 909.21,
 881.31,
 869.88,
 855.3,
 846.23,
 832.39]

In [157]:
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [158]:
n_steps = 5
X, y = splitSequence(Indonesia, n_steps = 5)

In [159]:
print(X)

[[1269.55 1081.11 1068.1  1574.76 1539.23]
 [1081.11 1068.1  1574.76 1539.23 1250.27]
 [1068.1  1574.76 1539.23 1250.27 1303.87]
 [1574.76 1539.23 1250.27 1303.87 1285.69]
 [1539.23 1250.27 1303.87 1285.69  773.92]
 [1250.27 1303.87 1285.69  773.92 1036.71]
 [1303.87 1285.69  773.92 1036.71  731.76]
 [1285.69  773.92 1036.71  731.76  738.57]
 [ 773.92 1036.71  731.76  738.57 1152.83]
 [1036.71  731.76  738.57 1152.83  829.93]
 [ 731.76  738.57 1152.83  829.93 1031.49]
 [ 738.57 1152.83  829.93 1031.49  761.93]
 [1152.83  829.93 1031.49  761.93 1001.39]
 [ 829.93 1031.49  761.93 1001.39  631.16]
 [1031.49  761.93 1001.39  631.16  795.62]
 [ 761.93 1001.39  631.16  795.62  849.42]
 [1001.39  631.16  795.62  849.42  907.96]
 [ 631.16  795.62  849.42  907.96 1484.56]
 [ 795.62  849.42  907.96 1484.56  772.38]
 [ 849.42  907.96 1484.56  772.38  909.21]
 [ 907.96 1484.56  772.38  909.21  881.31]
 [1484.56  772.38  909.21  881.31  869.88]
 [ 772.38  909.21  881.31  869.88  855.3 ]
 [ 909.21  

In [160]:
for i in range(len(X)):
    print(X[i], y[i])

[1269.55 1081.11 1068.1  1574.76 1539.23] 1250.27
[1081.11 1068.1  1574.76 1539.23 1250.27] 1303.87
[1068.1  1574.76 1539.23 1250.27 1303.87] 1285.69
[1574.76 1539.23 1250.27 1303.87 1285.69] 773.92
[1539.23 1250.27 1303.87 1285.69  773.92] 1036.71
[1250.27 1303.87 1285.69  773.92 1036.71] 731.76
[1303.87 1285.69  773.92 1036.71  731.76] 738.57
[1285.69  773.92 1036.71  731.76  738.57] 1152.83
[ 773.92 1036.71  731.76  738.57 1152.83] 829.93
[1036.71  731.76  738.57 1152.83  829.93] 1031.49
[ 731.76  738.57 1152.83  829.93 1031.49] 761.93
[ 738.57 1152.83  829.93 1031.49  761.93] 1001.39
[1152.83  829.93 1031.49  761.93 1001.39] 631.16
[ 829.93 1031.49  761.93 1001.39  631.16] 795.62
[1031.49  761.93 1001.39  631.16  795.62] 849.42
[ 761.93 1001.39  631.16  795.62  849.42] 907.96
[1001.39  631.16  795.62  849.42  907.96] 1484.56
[ 631.16  795.62  849.42  907.96 1484.56] 772.38
[ 795.62  849.42  907.96 1484.56  772.38] 909.21
[ 849.42  907.96 1484.56  772.38  909.21] 881.31
[ 907.96 148

In [161]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[1269.55]
  [1081.11]
  [1068.1 ]
  [1574.76]
  [1539.23]]

 [[1081.11]
  [1068.1 ]
  [1574.76]
  [1539.23]
  [1250.27]]]


In [162]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [163]:
model.layers

In [164]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_5 (LSTM)               (None, 50)                10400     
                                                                 
 dense_5 (Dense)             (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [165]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [166]:
model.fit(X, y, epochs=800, verbose=1)

Epoch 1/800
1/1 [==============================] - 1s 719ms/step - loss: 826586.6875 - accuracy: 0.0000e+00
Epoch 2/800
1/1 [==============================] - 0s 2ms/step - loss: 505820.0000 - accuracy: 0.0000e+00
Epoch 3/800
1/1 [==============================] - 0s 4ms/step - loss: 334225.7500 - accuracy: 0.0000e+00
Epoch 4/800
1/1 [==============================] - 0s 3ms/step - loss: 176091.1250 - accuracy: 0.0000e+00
Epoch 5/800
1/1 [==============================] - 0s 4ms/step - loss: 82044.3750 - accuracy: 0.0000e+00
Epoch 6/800
1/1 [==============================] - 0s 3ms/step - loss: 85631.6797 - accuracy: 0.0000e+00
Epoch 7/800
1/1 [==============================] - 0s 3ms/step - loss: 124269.8125 - accuracy: 0.0000e+00
Epoch 8/800
1/1 [==============================] - 0s 3ms/step - loss: 96237.3203 - accuracy: 0.0000e+00
Epoch 9/800
1/1 [==============================] - 0s 3ms/step - loss: 72193.9531 - accuracy: 0.0000e+00
Epoch 10/800
1/1 [==============================

In [167]:
test_data = np.array([1269.55, 1081.11, 1068.10, 1574.76, 1539.23])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[1269.55],
        [1081.11],
        [1068.1 ],
        [1574.76],
        [1539.23]]])

In [168]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 146ms/step
[[1309.3264]]
