In [59]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [60]:
df=pd.read_csv('historical_emissions.csv')
df

Country Data source                Sector  Gas    Unit  \
0                  World        CAIT  Total including LUCF  CO2  MtCO₂e   
1                  China        CAIT  Total including LUCF  CO2  MtCO₂e   
2          United States        CAIT  Total including LUCF  CO2  MtCO₂e   
3    European Union (27)        CAIT  Total including LUCF  CO2  MtCO₂e   
4                  India        CAIT  Total including LUCF  CO2  MtCO₂e   
..                   ...         ...                   ...  ...     ...   
190                Nauru        CAIT  Total including LUCF  CO2  MtCO₂e   
191               Tuvalu        CAIT  Total including LUCF  CO2  MtCO₂e   
192                 Niue        CAIT  Total including LUCF  CO2  MtCO₂e   
193                 Fiji        CAIT  Total including LUCF  CO2  MtCO₂e   
194                Ghana        CAIT  Total including LUCF  CO2  MtCO₂e   

         2018      2017      2016      2015      2014  ...      1999  \
0    36441.55  35588.70  35160.60  34521.91  34558.59  ...  24957.30   
1     9663.36   9367.67   9164.21   9120.27   9184.77  ...   2799.84   
2     4749.57   4581.90   4656.84   4563.52   4683.35  ...   5191.66   
3     2636.99   2692.12   2669.54   2321.61   2263.78  ...   3079.46   
4     2400.25   2267.16   2149.01   2085.38   2072.03  ...    683.00   
..        ...       ...       ...       ...       ...  ...       ...   
190      0.07      0.07      0.06      0.05      0.05  ...      0.09   
191      0.01      0.01      0.01      0.01      0.01  ...      0.01   
192      0.00      0.00      0.00      0.00      0.00  ...      0.01   
193     -0.65     -0.73     -0.81     -1.03     -1.24  ...     -1.74   
194     -8.82    -10.15    -10.82     44.53     43.77  ...     16.46   

         1998      1997      1996      1995      1994      1993      1992  \
0    24895.32  25292.92  24214.92  23890.22  23260.29  23124.00  22988.29   
1     2882.75   2779.27   2715.50   2735.48   2414.50   2294.12   2068.77   
2     5172.06   5129.29   4864.46   4708.31   4654.52   4581.76   4461.62   
3     3134.03   3142.23   3210.93   3113.68   3060.09   3072.40   3133.06   
4      618.73    600.38    555.60    519.98    466.79    431.31    409.09   
..        ...       ...       ...       ...       ...       ...       ...   
190      0.10      0.10      0.10      0.11      0.11      0.11      0.12   
191      0.01      0.01      0.01      0.01      0.01      0.01      0.01   
192      0.01      0.01      0.01      0.01      0.01      0.01      0.01   
193     -1.76     -1.74     -1.72     -1.78     -1.79     -1.79     -1.78   
194     15.98     14.18     13.98     13.60     13.34     13.07     12.96   

         1991      1990  
0    23056.40  22849.92  
1     1952.78   1823.96  
2     4389.50   4426.40  
3     3247.48   3286.44  
4      386.17    341.32  
..        ...       ...  
190      0.13      0.13  
191      0.00      0.00  
192      0.01      0.01  
193     -1.81     -1.81  
194     12.44     12.67  

[195 rows x 34 columns]

In [61]:
df=df.drop(columns=['Data source','Sector','Gas','Unit'])

In [62]:
# negaraASEAN=['Indonesia', 'Thailand', 'Cambodia', 'Myanmar', 'Malaysia','Singapore','Philippines','Vietnam','Laos','Brunei']

In [63]:
df_clean=df.loc[df['Country']=='Indonesia']

In [64]:
df_clean

Country     2018     2017    2016     2015     2014     2013     2012  \
5  Indonesia  1269.55  1081.11  1068.1  1574.76  1539.23  1250.27  1303.87   

      2011    2010  ...    1999    1998     1997    1996    1995    1994  \
5  1285.69  773.92  ...  849.42  907.96  1484.56  772.38  909.21  881.31   

     1993   1992    1991    1990  
5  869.88  855.3  846.23  832.39  

[1 rows x 30 columns]

In [65]:
# for i in range(len(df_clean)):
row=df_clean.columns.values.tolist()
row.pop(0)
# print(row)
country=df_clean.iloc[:,0].values.tolist()
# country

In [66]:
df_trans=df_clean.T

In [67]:
new_header = df_trans.iloc[0] #grab the first row for the header
df_trans = df_trans[1:] #take the data less the header row
df_trans.columns = new_header #set the header row as the df header

In [68]:
df_trans

Country Indonesia
2018      1269.55
2017      1081.11
2016       1068.1
2015      1574.76
2014      1539.23
2013      1250.27
2012      1303.87
2011      1285.69
2010       773.92
2009      1036.71
2008       731.76
2007       738.57
2006      1152.83
2005       829.93
2004      1031.49
2003       761.93
2002      1001.39
2001       631.16
2000       795.62
1999       849.42
1998       907.96
1997      1484.56
1996       772.38
1995       909.21
1994       881.31
1993       869.88
1992        855.3
1991       846.23
1990       832.39

In [69]:
df_testing=df_trans.iloc[:10]
df_testing.head()


Country Indonesia
2018      1269.55
2017      1081.11
2016       1068.1
2015      1574.76
2014      1539.23

In [70]:
df_training=df_trans.iloc[10:]

In [71]:
Indonesia=df_training.iloc[::-1,0].values.tolist()
Indonesia

[832.39,
 846.23,
 855.3,
 869.88,
 881.31,
 909.21,
 772.38,
 1484.56,
 907.96,
 849.42,
 795.62,
 631.16,
 1001.39,
 761.93,
 1031.49,
 829.93,
 1152.83,
 738.57,
 731.76]

In [72]:
def splitSequence(seq, n_steps):
    
    #deklarasi list kosong X dan y
    X = []
    y = []
    
    for i in range(len(seq)):
        #Index terakhir sebagai label
        lastIndex = i + n_steps
        
        #jika lastIndex > panjang sekuens, break
        if lastIndex > len(seq) - 1:
            break
            
        #buat sekuens input dan output
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [73]:
n_steps = 4
X, y = splitSequence(Indonesia, n_steps = 4)

In [74]:
print(X)

[[ 832.39  846.23  855.3   869.88]
 [ 846.23  855.3   869.88  881.31]
 [ 855.3   869.88  881.31  909.21]
 [ 869.88  881.31  909.21  772.38]
 [ 881.31  909.21  772.38 1484.56]
 [ 909.21  772.38 1484.56  907.96]
 [ 772.38 1484.56  907.96  849.42]
 [1484.56  907.96  849.42  795.62]
 [ 907.96  849.42  795.62  631.16]
 [ 849.42  795.62  631.16 1001.39]
 [ 795.62  631.16 1001.39  761.93]
 [ 631.16 1001.39  761.93 1031.49]
 [1001.39  761.93 1031.49  829.93]
 [ 761.93 1031.49  829.93 1152.83]
 [1031.49  829.93 1152.83  738.57]]


In [75]:
for i in range(len(X)):
    print(X[i], y[i])

[832.39 846.23 855.3  869.88] 881.31
[846.23 855.3  869.88 881.31] 909.21
[855.3  869.88 881.31 909.21] 772.38
[869.88 881.31 909.21 772.38] 1484.56
[ 881.31  909.21  772.38 1484.56] 907.96
[ 909.21  772.38 1484.56  907.96] 849.42
[ 772.38 1484.56  907.96  849.42] 795.62
[1484.56  907.96  849.42  795.62] 631.16
[907.96 849.42 795.62 631.16] 1001.39
[ 849.42  795.62  631.16 1001.39] 761.93
[ 795.62  631.16 1001.39  761.93] 1031.49
[ 631.16 1001.39  761.93 1031.49] 829.93
[1001.39  761.93 1031.49  829.93] 1152.83
[ 761.93 1031.49  829.93 1152.83] 738.57
[1031.49  829.93 1152.83  738.57] 731.76


In [76]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[832.39]
  [846.23]
  [855.3 ]
  [869.88]]

 [[846.23]
  [855.3 ]
  [869.88]
  [881.31]]]


In [77]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [78]:
model.layers

In [79]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_2 (LSTM)               (None, 50)                10400     
                                                                 
 dense_2 (Dense)             (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [80]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredLogarithmicError(), metrics=['accuracy'])

In [81]:
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
1/1 [==============================] - 1s 670ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 3/500
1/1 [==============================] - 0s 3ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 5/500
1/1 [==============================] - 0s 6ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 8/500
1/1 [==============================] - 0s 5ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 46.0108 - accuracy: 0.0000e+00
Epoch 10/500
1/1 [==============================] - 0s 4ms/step - loss: 46.0108 

In [82]:
X_test, y_test = splitSequence(df_testing.iloc[::-1,0].values.tolist(), n_steps = 5)

In [83]:
X_test

array([[1036.71,  773.92, 1285.69, 1303.87, 1250.27],
       [ 773.92, 1285.69, 1303.87, 1250.27, 1539.23],
       [1285.69, 1303.87, 1250.27, 1539.23, 1574.76],
       [1303.87, 1250.27, 1539.23, 1574.76, 1068.1 ],
       [1250.27, 1539.23, 1574.76, 1068.1 , 1081.11]])

In [84]:
y_test

array([1539.23, 1574.76, 1068.1 , 1081.11, 1269.55])

In [85]:
predictNextNumber = model.predict(X_test, verbose=1)
print(predictNextNumber)

ValueError: in user code:

    File "c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 1801, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 1790, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 1783, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\training.py", line 1751, in predict_step
        return self(x, training=False)
    File "c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential_2" is incompatible with the layer: expected shape=(None, 4, 1), found shape=(None, 5)


In [ ]:
y_test

array([1539.23, 1574.76, 1068.1 , 1081.11, 1269.55])